### ISSUE TITLE
Should This Repository Be Archived?

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-front-end-template#267] opened 2023-04-19 15:38 UTC
The main branch has not seen a commit in over a year, it seems.

**Comment by glitch-txs** [comment] 2023-04-22 06:32
Is there any alternative repo to look into?

**Comment by ltfschoen** [comment] 2023-05-09 18:29
The repo's README should specifically state that it requires Yarn 3.x not Yarn 1.x for starters, and provide some guidance on configuring it, not just a link to the Yarn website, since Yarn 3 setup even caught me by surprise.

That's the cause of some of the open issues where users encountered Yarn errors and might have even given up on bothering to try to use Substrate all together. It's a show-stopper for some. If hate to think of how many users don't get passed that step but don't spend the time digging through the open issues for the solution, or just notice how long it's been since it was last updated and just walk away immediately. 

I tried to created a PR to Dockerise it here https://github.com/substrate-developer-hub/substrate-front-end-template/pull/261 since then users are less likely to get stumped during installation steps too, but it doesn't seem like anyone was available or interested in reviewing it, so I haven't touched the repo since.

There are numerous open PRs and issues that have been open for more than 6 months often with simple fixes and should have been closed months ago, maybe those should be fixed before archiving it. 

This is all surprising given that this repo would likely be the goto repo for any user wanting to create a dapp on the Polkadot network that either interacts with smart contracts or directly with a one or more chains. 

I'd be afraid to
So Why would anyone waste their time contributing to this repo when nobody seems to be maintaining it

**Comment by sacha-l** [comment] 2023-05-24 12:15
I don't think this repo should be archive for the reasons @ltfschoen provides above. I'm working on getting it updated. 

Thanks for all your help @ltfschoen  - it's very appreciated. It's unfortunate that this repo hasn't been a priority to be actively maintained and I'm sorry some of your PRs have been ignored for so long. I'll make sure the repo gets more attention. Your active involvement is much appreciated.

**Closed by sacha-l** 2023-05-24 12:15 UTC
